# Author: Tom Keur <mail@tomkeur.net>
version: "3.3"
services:
  php_web_odin:
    image: php:7.1.9-apache
    volumes:
      - ../www:/var/www/html
    ports:
      - 7080:80
  php_web_dva:
    image: php:7.1.9-apache
    volumes:
      - ../www:/var/www/html
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
    depends_on:
      - php_web_odin
      - php_web_dva