# Author: Tom Keur <mail@tomkeur.net>
version: "3.3"
services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf/conf.d:/etc/nginx/conf.d
      - ../www:/var/www/html